image:
  main:
    repository: machines/filestash
    pullPolicy: IfNotPresent
    # tag: latest

global:
  main:
    ports:
      - containerPort: 8334
    options:
      application_url: https://files.example.com
    environments: {}
      # - name: key
      #  value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8334
      targetPort: 8334

resources:
  limits:
    main:
      memory: 512Mi
  requests:
    main:
      storage: 256Mi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}