apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-web"
  namespace: "{{ if eq .Release.Namespace "default" }}vaultwarden-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  replicas: {{ .Values.replicaCount | default (printf "%d" 1) }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-web"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-web"
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{-  with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "{{ .Release.Name }}-web-init"
          image: busybox
          command:
            - sh
            - -c
            - |
            {{- if eq .Values.global.postgres.internal.enabled true }}
              until nc -z -v -w30 {{ .Release.Name }}-postgres 5432
            {{- else }}
              until nc -z -v -w30 {{ .Values.global.postgres.external.host }} {{ .Values.global.postgres.external.port }}
            {{- end }}
              do
                echo "Waiting for the database to be ready..."
                sleep 5
              done
      containers:
        - name: "{{ .Release.Name }}-web"
          image: {{ template "vaultwarden.web.image" . }}
          env:
            - name: DATABASE_URL
              value: {{ template "postgres.credentials" . }}
            - name: ENABLE_WEBSOCKET
              value: {{ .Values.global.web.options.enable_websocket | quote }}
            - name: SIGNUPS_ALLOWED
              value: {{ .Values.global.web.options.signups_allowed | quote }}
            - name: INVITATIONS_ALLOWED
              value: {{ .Values.global.web.options.invitations_allowed | quote }}
            - name: SHOW_PASSWORD_HINT
              value: {{ .Values.global.web.options.show_password_hint | quote }}
            - name: ROCKET_PORT
              value: {{ .Values.global.web.options.rocket_port | quote }}
          {{- range .Values.global.web.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- with .Values.global.web.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources.limits.web }}
          resources:
            limits:
              {{- toYaml . | nindent 14 }}
          {{- end }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /data
      volumes:
        - name: "{{ .Release.Name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data-pvc"

{{ if eq .Values.global.postgres.internal.enabled true }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: "{{ if eq .Release.Namespace "default" }}vaultwarden-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  replicas: {{ .Values.replicaCount | default (printf "%d" 1) }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-postgres"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-postgres"
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{-  with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: "{{ .Release.Name }}-postgres"
          image: {{ template "vaultwarden.postgres.image" . }}
          env:
            - name: POSTGRES_DB
            {{- if .Values.global.postgres.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres
                  key: {{ .Values.global.postgres.secret.databaseKey | quote }}
            {{- else }}
              value: {{ .Values.global.postgres.options.database | quote }}
            {{- end }}
            - name: POSTGRES_USER
            {{- if .Values.global.postgres.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres
                  key: {{ .Values.global.postgres.secret.usernameKey | quote }}
            {{- else }}
              value: {{ .Values.global.postgres.options.username | quote }}
            {{- end }}
            - name: POSTGRES_PASSWORD
            {{- if .Values.global.postgres.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgres
                  key: {{ .Values.global.postgres.secret.passwordKey | quote }}
            {{- else }}
              value: {{ .Values.global.postgres.options.password | quote }}
            {{- end }}
          {{- range .Values.global.postgres.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: "{{ .Release.Name }}-postgres-data"
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: "{{ .Release.Name }}-postgres-data"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-postgres-pvc"
{{- end }}