{{- if .Values.global.postgres.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: "{{ if eq .Release.Namespace "default" }}vaultwarden-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{- $credentials := split " " (include "postgres.credentials" .) }}
  {{- $username := $credentials._0 }}
  {{- $password := $credentials._1 }}
  {{- $database := $credentials._2 }}
  {{- $host := $credentials._3 }}
  {{- $port := $credentials._4 }}
  {{ .Values.global.postgres.secret.usernameKey }}: "{{ $username | b64enc }}"
  {{ .Values.global.postgres.secret.passwordKey }}: "{{ $password | b64enc }}"
  {{ .Values.global.postgres.secret.databaseKey }}: "{{ $database | b64enc }}"
  conn_string: {{ printf "postgresql://%s:%s@%s:%s/%s" $username $password $host $port $database | b64enc | quote }}
{{- end }}