apiVersion: v2
name: umami
description: A self hosted web analytics platform
type: application
version: 2.3.0
appVersion: '2.16'
projectUrl: https://github.com/umami-software/umami
maintainers:
- name: Taha
  email: mt190502@mtaha.dev
