apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
  {{ if eq .Release.Namespace "default" }}
  {{- printf "namespace: %s" "commafeed-k8s" -}}
  {{ else }}
  {{- printf "namespace: %s" .Release.Namespace -}}
  {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.requests.web.storage }}
{{ if eq .Values.global.postgres.internal.enabled true }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-postgres-pvc
  {{ if eq .Release.Namespace "default" }}
  {{- printf "namespace: %s" "commafeed-k8s" -}}
  {{ else }}
  {{- printf "namespace: %s" .Release.Namespace -}}
  {{ end }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.resources.requests.postgres.storage }}
{{- end }}