---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-data-pvc"
  namespace: "{{ if eq .Release.Namespace "default" }}commafeed-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.resources.requests.web.storage }}"

{{ if eq .Values.global.postgres.internal.enabled true }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgres-pvc"
  namespace: "{{ if eq .Release.Namespace "default" }}commafeed-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.resources.requests.postgres.storage }}"
{{- end }}