---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-web"
  namespace: "{{ if eq .Release.Namespace "default" }}memos-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  replicas: {{ .Values.replicaCount | default (printf "%d" 1) }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-web"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-web"
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "{{ .Release.Name }}-web-init"
          image: busybox
          command:
            - sh
            - -c
            - |
            {{- if and .Values.global.postgres.cnpg.enabled }}
              until nc -z -v -w30 {{ .Release.Name }}-postgres-rw 5432
            {{- else if and .Values.global.postgres.internal.enabled }}
              until nc -z -v -w30 {{ .Release.Name }}-postgres 5432
            {{- else }}
              until nc -z -v -w30 {{ .Values.global.postgres.external.host }} {{ .Values.global.postgres.external.port }}
            {{- end }}
              do
                echo "Waiting for the database to be ready..."
                sleep 5
              done
      containers:
        - name: "{{ .Release.Name }}-web"
          image: {{ template "memos.web.image" . }}
          env:
            {{- if or (eq (.Values.global.postgres.secret.autoCreate | toString) "kustomize") (eq (.Values.global.postgres.secret.autoCreate | toString) "true") }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.global.postgres.secret.name }}{{ .Values.global.postgres.secret.name }}{{ else }}{{ .Release.Name }}-postgres{{ end }}
                  key: {{ .Values.global.postgres.secret.usernameKey | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.global.postgres.secret.name }}{{ .Values.global.postgres.secret.name }}{{ else }}{{ .Release.Name }}-postgres{{ end }}
                  key: {{ .Values.global.postgres.secret.passwordKey | quote }}
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.global.postgres.secret.name }}{{ .Values.global.postgres.secret.name }}{{ else }}{{ .Release.Name }}-postgres{{ end }}
                  key: {{ .Values.global.postgres.secret.databaseKey | quote }}
            - name: DB_HOST
              {{- if eq .Values.global.postgres.internal.enabled true }}
              value: {{ .Release.Name }}-postgres{{ if eq .Values.global.postgres.cnpg.enabled true }}-rw{{ end }}
              {{- else }}
              value: {{ .Values.global.postgres.external.host }}
              {{- end }}
            - name: DB_PORT
              {{- if eq .Values.global.postgres.internal.enabled true }}
              value: "5432"
              {{- else }}
              value: {{ .Values.global.postgres.external.port | quote }}
              {{- end }}
          {{- end }}
            - name: SSL_MODE
              value: {{ .Values.global.postgres.options.sslmode }}
            - name: MEMOS_DRIVER
              value: "postgres"
            - name: MEMOS_DSN
              value: {{ template "postgres.credentials" . }}
          {{- range .Values.global.web.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- with .Values.global.web.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources.limits.web }}
          resources:
            limits:
              {{- toYaml . | nindent 14 }}
          {{- end }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /var/opt/memos
      volumes:
        - name: "{{ .Release.Name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data-pvc"

{{ if and .Values.global.postgres.internal.enabled (eq .Values.global.postgres.cnpg.enabled false) }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: "{{ if eq .Release.Namespace "default" }}memos-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  replicas: {{ .Values.replicaCount | default (printf "%d" 1) }}
  podManagementPolicy: {{ .Values.global.postgres.settings.podManagementPolicy | default "Parallel" | quote }}
  serviceName: "{{ .Release.Name }}-postgres"
  {{- if .Values.global.postgres.settings.updateStrategy }}
  updateStrategy:
    type: {{ .Values.global.postgres.settings.updateStrategy.type | default "RollingUpdate" | quote }}
  {{- end }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-postgres"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-postgres"
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: "{{ .Release.Name }}-postgres-init"
          image: busybox
          command:
            - sh
            - -c
            - |
              [ -d "/mnt/lost+found" ] && rm -rf /mnt/lost+found
              exit 0
          volumeMounts:
            - name: "database"
              mountPath: /mnt
      containers:
        - name: "{{ .Release.Name }}-postgres"
          image: {{ template "memos.postgres.image" . }}
          env:
            - name: POSTGRES_DB
            {{- if .Values.global.postgres.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.global.postgres.secret.name }}{{ .Values.global.postgres.secret.name }}{{ else }}{{ .Release.Name }}-postgres{{ end }}
                  key: {{ .Values.global.postgres.secret.databaseKey | quote }}
            {{- else }}
              value: {{ .Values.global.postgres.options.database | quote }}
            {{- end }}
            - name: POSTGRES_USER
            {{- if .Values.global.postgres.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.global.postgres.secret.name }}{{ .Values.global.postgres.secret.name }}{{ else }}{{ .Release.Name }}-postgres{{ end }}
                  key: {{ .Values.global.postgres.secret.usernameKey | quote }}
            {{- else }}
              value: {{ .Values.global.postgres.options.username | quote }}
            {{- end }}
            - name: POSTGRES_PASSWORD
            {{- if .Values.global.postgres.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.global.postgres.secret.name }}{{ .Values.global.postgres.secret.name }}{{ else }}{{ .Release.Name }}-postgres{{ end }}
                  key: {{ .Values.global.postgres.secret.passwordKey | quote }}
            {{- else }}
              value: {{ .Values.global.postgres.options.password | quote }}
            {{- end }}
          {{- range .Values.global.postgres.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: "database"
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: "database"
  {{- if .Values.global.postgres.settings.persistence.claimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.global.postgres.settings.persistence.claimRetentionPolicy.whenDeleted | default "Retain" | quote }}
    whenScaled: {{ .Values.global.postgres.settings.persistence.claimRetentionPolicy.whenScaled | default "Retain" | quote }}
  {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "database"
        namespace: "{{ if eq .Release.Namespace "default" }}memos-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
      spec:
        accessModes:
        {{- if .Values.global.postgres.settings.persistence.accessModes }}
        {{- toYaml .Values.global.postgres.settings.persistence.accessModes | nindent 8 }} 
        {{- else }}
          - ReadWriteOnce
        {{- end }}
        resources:
          requests:
            storage: "{{ .Values.resources.requests.postgres.storage }}"
{{- end }}