{{- if and .Values.global.main.appSecret.enabled (eq (.Values.global.main.appSecret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.global.main.appSecret.name }}{{ .Values.global.main.appSecret.name }}{{ else }}{{ .Release.Name }}-secret{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.global.main.appSecret.key }}: "{{ .Values.global.main.options.app_secret | b64enc }}"
{{- end }}