image:
  main:
    repository: athou/commafeed
    pullPolicy: IfNotPresent
    # tag: 5.7.0-postgresql
  postgresql:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: 17

global:
  main:
    ports:
      - containerPort: 8082
    options:
      publicUrl: https://rss.example.com
    environments: {}
      # - name: key
      #  value: value

  postgresql:
    external:
      enabled: false
      host: 127.0.0.1
      port: 5432
    internal:
      enabled: true
    cnpg:
      enabled: false
      replicas: 3
      primaryUpdateStrategy: unsupervised
    secret:
      enabled: true
      autoCreate: true
      name: commafeed-postgresql
      usernameKey: username
      passwordKey: password
      databaseKey: database
    options:
      database: commafeed
      username: commafeed
      password: commafeed
    settings: #~ ignored if cnpg.enabled
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}
      # - name: key
      #   value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082

resources:
  limits:
    main:
      memory: 512Mi
    postgresql:
      memory: 512Mi
  requests:
    main:
      storage: 256Mi
    postgresql:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}