image:
  web:
    repository: athou/commafeed
    pullPolicy: IfNotPresent
    #tag: 5.1.1-postgresql
  postgres:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: 17

global:
  web:
    ports:
      - containerPort: 8082
    options:
      publicUrl: localhost
    environments: {}
      #- name: key
      #  value: value

  postgres:
    external:
      enabled: false
      host: 127.0.0.1
      port: 5432
    internal:
      enabled: true
    secret:
      enabled: true
      autoCreate: true
      name: commafeed-postgres
      usernameKey: postgres_username
      passwordKey: postgres_password
      databaseKey: postgres_database
    options:
      database: commafeed
      username: commafeed
      password: commafeed
    settings:
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}
      #- name: key
      #  value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082

resources:
  limits:
    web:
      cpu: 1
      memory: 512Mi
    postgres:
      cpu: 1
      memory: 512Mi
  requests:
    web:
      storage: 256Mi
    postgres:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
