{{- if and .Values.main.appSecret.enabled (eq (.Values.main.appSecret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.main.appSecret.name }}{{ .Values.main.appSecret.name }}{{ else }}{{ .Release.Name }}-secret{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.main.appSecret.key }}: "{{ .Values.main.options.app_secret | b64enc }}"
{{- end }}

{{- if and .Values.postgresql.selected .Values.postgresql.secret.enabled (eq (.Values.postgresql.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.postgresql.secret.name }}{{ .Values.postgresql.secret.name }}{{ else }}{{ .Release.Name }}-postgresql{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.postgresql.secret.usernameKey }}: "{{ .Values.postgresql.options.username | b64enc }}"
  {{ .Values.postgresql.secret.passwordKey }}: "{{ .Values.postgresql.options.password | b64enc }}"
  {{ .Values.postgresql.secret.databaseKey }}: "{{ .Values.postgresql.options.database | b64enc }}"
{{- end }}

{{- if and .Values.mysql.selected .Values.mysql.secret.enabled (eq (.Values.mysql.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.mysql.secret.usernameKey }}: "{{ .Values.mysql.options.username | b64enc }}"
  {{ .Values.mysql.secret.passwordKey }}: "{{ .Values.mysql.options.password | b64enc }}"
  {{ .Values.mysql.secret.databaseKey }}: "{{ .Values.mysql.options.database | b64enc }}"
  {{ .Values.mysql.secret.rootPasswordKey }}: "{{ .Values.mysql.options.rootPassword | b64enc }}"
{{- end }}