image:
  web:
    repository: ghost
    pullPolicy: IfNotPresent
    #tag: 5.109.2
  mysql:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: 8

global:
  web:
    ports:
      - containerPort: 2368
    options:
      ghost_url: https://ghost.example.com
      ghost_admin_url: https://ghost.example.com/ghost
    environments: {}
      # - name: key
      #  value: value

  mysql:
    external:
      enabled: false
      host: 127.0.0.1
      port: 3306
    internal:
      enabled: true
    secret:
      enabled: true
      autoCreate: true
      name: ghost-mysql
      usernameKey: mysql_username
      passwordKey: mysql_password
      rootPasswordKey: mysql_root_password
      databaseKey: mysql_database
    options:
      database: ghost
      username: ghost
      password: ghost
      rootPassword: my_secret_root_password
    settings:
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}
      # - name: key
      #   value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 2368
      targetPort: 2368

resources:
  limits:
    web:
      memory: 512Mi
    mysql:
      memory: 512Mi
  requests:
    web:
      storage: 1Gi
    mysql:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
