image:
  main:
    repository: ghcr.io/bouquet2/copilot-api-docker
    pullPolicy: IfNotPresent
    # tag: 0.1.1

main:
  ports:
    - containerPort: 4141
  extraArgs:
    - --vision
  environments: {}
    # - name: key
    #  value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 4141
      targetPort: 4141

resources:
  limits:
    main:
      memory: 512Mi
  requests:
    main:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}