image:
  main:
    repository: ghcr.io/mt190502/docker-anki-server
    pullPolicy: IfNotPresent
    # tag: 25.02.4

global:
  main:
    ports:
      - containerPort: 8080
    appSecret:
      enabled: true
      autoCreate: true
      name: anki-server-secret
      key: admin_user_secret
    options:
      admin_user_secret: "username:password"
    environments: {}
      # - name: key
      #  value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

resources:
  limits:
    main:
      memory: 512Mi
  requests:
    main:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}