image:
  main:
    repository: ghcr.io/mt190502/docker-anki-sync-server
    pullPolicy: IfNotPresent
    # tag: 25.02.4

global:
  main:
    ports:
      - containerPort: 8080
    accounts:
      - key: SYNC_USER1
        name: username
        password: password # (optional if using appSecret with kustomize option)
        secret: 
          enabled: true
          autoCreate: true
          name: username1-secret
          key: cred
      # - key: SYNC_USER2
      #   name: username2
      #   password: password2
      #   secret: 
      #     enabled: true
      #     autoCreate: true
      #     name: username2-secret
      #     key: cred
    environments: {}
      # - name: key
      #  value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080

resources:
  limits:
    main:
      memory: 512Mi
  requests:
    main:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}