image:
  main:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    pullPolicy: IfNotPresent
    # tag: 2.15.1
  postgresql:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: 17
  redis:
    repository: redis
    pullPolicy: IfNotPresent
    tag: 7

global:
  main:
    ports:
      - containerPort: 8000
    appSecret:
      enabled: true
      autoCreate: true
      name: paperless-ngx-secret
      key: app_secret
    options:
      app_secret: my_strong_secret
      paperless_port: 8000
      paperless_url: https://paperless.example.com
      usermap_uid: 1000
      usermap_gid: 1000
    environments: {}
      # - name: key
      #  value: value

  redis:
    enabled: true
    external:
      enabled: false
      host: 127.0.0.1
      port: 6379
    internal:
      enabled: true
    settings:
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}

  postgresql:
    external:
      enabled: false
      host: 127.0.0.1
      port: 5432
    internal:
      enabled: true
    cnpg:
      enabled: false
      replicas: 3
      primaryUpdateStrategy: unsupervised
    secret:
      enabled: true
      autoCreate: true
      name: paperless-ngx-postgresql
      usernameKey: username
      passwordKey: password
      databaseKey: database
    options:
      database: paperless-ngx
      username: paperless-ngx
      password: paperless-ngx
    settings: #~ ignored if cnpg.enabled
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}
      # - name: key
      #   value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

resources:
  limits:
    main:
      memory: 2Gi
    redis:
      memory: 512Mi
    postgresql:
      memory: 512Mi
  requests:
    main:
      storage: 1Gi
    redis:
      storage: 1Gi
    postgresql:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}