image:
  web:
    repository: ghcr.io/paperless-ngx/paperless-ngx
    pullPolicy: IfNotPresent
    #tag: 2.12.1
  postgres:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: 17
  broker:
    repository: redis
    pullPolicy: IfNotPresent
    tag: 7

global:
  web:
    ports:
      - containerPort: 8000
    appSecret:
      enabled: true
      autoCreate: true
      name: paperless-ngx-secret
      key: app_secret
    options:
      paperless_port: 8000
      paperless_url: https://localhost
      paperless_app_secret: my_strong_secret
      usermap_uid: 1000
      usermap_gid: 1000
    environments: {}
      # - name: key
      #   value: value

  redis:
    external:
      enabled: false
      host: 127.0.0.1
      port: 6379
    internal:
      enabled: true
    environments: {}

  postgres:
    external:
      enabled: false
      host: 127.0.0.1
      port: 5432
    internal:
      enabled: true
    cnpg:
      enabled: false
      replicas: 3
      primaryUpdateStrategy: unsupervised
    secret:
      enabled: true
      autoCreate: true
      name: paperless-ngx-postgres
      usernameKey: username
      passwordKey: password
      databaseKey: database
    options:
      database: paperless-ngx
      username: paperless-ngx
      password: paperless-ngx
    settings: #~ ignored if cnpg.enabled
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}
      # - name: key
      #   value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000

resources:
  limits:
    web:
      cpu: 1
      memory: 2048Mi
    redis:
      memory: 512Mi
    postgres:
      memory: 512Mi
  requests:
    web:
      storage: 1Gi
    media:
      storage: 2Gi
    export:
      storage: 512Mi
    broker:
      storage: 1Gi
    postgres:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
