image:
  repository: tomsquest/docker-radicale
  pullPolicy: IfNotPresent
  # tag: 3.4.0.0

global:
  main:
    ports:
      - containerPort: 5232
    environments: {}
      # - name: key
      #  value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5232
      targetPort: 5232

resources:
  limits:
    main:
      memory: 512Mi
  requests:
    main:
      storage: 256Mi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
