{{- if and .Values.global.web.appSecret.enabled (eq (.Values.global.web.appSecret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.global.web.appSecret.name }}{{ .Values.global.web.appSecret.name }}{{ else }}{{ .Release.Name }}-web{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}paperless-ngx-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.global.web.appSecret.key }}: "{{ .Values.global.web.options.paperless_app_secret | b64enc }}"
{{- end }}

{{- if and .Values.global.postgres.secret.enabled (eq (.Values.global.postgres.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.global.postgres.secret.name }}{{ .Values.global.postgres.secret.name }}{{ else }}{{ .Release.Name }}-postgres{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}paperless-ngx-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.global.postgres.secret.usernameKey }}: "{{ .Values.global.postgres.options.username | b64enc }}"
  {{ .Values.global.postgres.secret.passwordKey }}: "{{ .Values.global.postgres.options.password | b64enc }}"
  {{ .Values.global.postgres.secret.databaseKey }}: "{{ .Values.global.postgres.options.database | b64enc }}"
{{- end }}