---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-main"
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: "{{ .Release.Name }}-main"
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
    
{{ if and .Values.global.postgresql.internal.enabled (eq .Values.global.postgresql.cnpg.enabled false) }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-postgresql"
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  ports:
    - port: 5432
  selector:
    app: "{{ .Release.Name }}-postgresql"
{{- end }}