{{- if and .Values.global.postgres.secret.enabled (eq (.Values.global.postgres.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Release.Name }}-postgres"
  namespace: "{{ if eq .Release.Namespace "default" }}codimd-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{- $credentials := split " " (include "postgres.credentials" (dict "Release" .Release "Values" .Values "raw" true)) }}
  {{- $username := $credentials._0 }}
  {{- $password := $credentials._1 }}
  {{- $database := $credentials._2 }}
  {{- $host := $credentials._3 }}
  {{- $port := $credentials._4 }}
  {{ .Values.global.postgres.secret.usernameKey }}: "{{ $username | b64enc }}"
  {{ .Values.global.postgres.secret.passwordKey }}: "{{ $password | b64enc }}"
  {{ .Values.global.postgres.secret.databaseKey }}: "{{ $database | b64enc }}"
{{- end }}