---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-main"
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  replicas: {{ .Values.replicaCount | default (printf "%d" 1) }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-main"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-main"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: "{{ .Release.Name }}-main-init"
          image: busybox
          command:
            - sh
            - -c
            - |
              {{- if .Values.mysql.internal.enabled }}
              until nc -z -v -w30 {{ .Release.Name }}-mysql 3306
              {{- else }}
              until nc -z -v -w30 {{ .Values.mysql.external.host }} {{ .Values.mysql.external.port }}
              {{- end }}
              do
                echo "Waiting for the database to be ready..."
                sleep 5
              done
      containers:
        - name: "{{ .Release.Name }}-main"
          image: {{ template "<<<APPNAME>>>.main.image" . }}
          env:
            - name: DB_USERNAME
              {{- if .Values.mysql.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
                  key: {{ .Values.mysql.secret.usernameKey | quote }}
              {{- else }}
              value: {{ .Values.mysql.options.username | quote }}
              {{- end }}
            - name: DB_PASSWORD
              {{- if .Values.mysql.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
                  key: {{ .Values.mysql.secret.passwordKey | quote }}
              {{- else }}
              value: {{ .Values.mysql.options.password | quote }}
              {{- end }}
            - name: DB_DATABASE
              {{- if .Values.mysql.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
                  key: {{ .Values.mysql.secret.databaseKey | quote }}
              {{- else }}
              value: {{ .Values.mysql.options.database | quote }}
              {{- end }}
            - name: DB_HOST
              {{- if .Values.mysql.internal.enabled }}
              value: {{ .Release.Name }}-mysql
              {{- else }}
              value: {{ .Values.mysql.external.host }}
              {{- end }}
            - name: DB_PORT
              {{- if .Values.mysql.internal.enabled }}
              value: "3306"
              {{- else }}
              value: {{ .Values.mysql.external.port | quote }}
              {{- end }}
            - name: DB_CONNECTION_STRING
              value: {{ template "mysql.credentials" . }}
          {{- if .Values.main.appSecret.enabled }}
            - name: APP_SECRET
              {{- if or (eq (.Values.main.appSecret.autoCreate | toString) "true") (eq (.Values.main.appSecret.autoCreate | toString) "kustomize") }}
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.main.appSecret.name }}
                  key: {{ .Values.main.appSecret.key | quote }}
              {{- else }}
              value: {{ .Values.main.options.app_secret | quote }}
              {{- end }}
          {{- end }}
          {{- range .Values.main.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- with .Values.main.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources.limits.main }}
          resources:
            limits:
              {{- toYaml . | nindent 14 }}
          {{- end }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /opt/<<<APPNAME>>>/
              subPath: subpath
      volumes:
        - name: "{{ .Release.Name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data-pvc"

{{ if .Values.mysql.internal.enabled }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "{{ .Release.Name }}-mysql"
  namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  replicas: {{ .Values.replicaCount | default (printf "%d" 1) }}
  podManagementPolicy: {{ .Values.mysql.settings.podManagementPolicy | default "Parallel" | quote }}
  serviceName: "{{ .Release.Name }}-mysql"
  {{- if .Values.mysql.settings.updateStrategy }}
  updateStrategy:
    type: {{ .Values.mysql.settings.updateStrategy.type | default "RollingUpdate" | quote }}
  {{- end }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-mysql"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-mysql"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      initContainers:
        - name: "{{ .Release.Name }}-mysql-init"
          image: busybox
          command:
            - sh
            - -c
            - |
              [ -d "/mnt/lost+found" ] && rm -rf /mnt/lost+found
              exit 0
          volumeMounts:
            - name: "database"
              mountPath: /mnt
      containers:
        - name: "{{ .Release.Name }}-mysql"
          image: {{ template "<<<APPNAME>>>.mysql.image" . }}
          env:
            - name: {{ if eq .Values.image.mysql.repository "mariadb"}}MARIADB{{ else }}MYSQL{{ end }}_DATABASE
              {{- if .Values.mysql.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
                  key: {{ .Values.mysql.secret.databaseKey | quote }}
              {{- else }}
              value: {{ .Values.mysql.options.database | quote }}
              {{- end }}
            - name: {{ if eq .Values.image.mysql.repository "mariadb"}}MARIADB{{ else }}MYSQL{{ end }}_USER
              {{- if .Values.mysql.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
                  key: {{ .Values.mysql.secret.usernameKey | quote }}
              {{- else }}
              value: {{ .Values.mysql.options.username | quote }}
              {{- end }}
            - name: {{ if eq .Values.image.mysql.repository "mariadb"}}MARIADB{{ else }}MYSQL{{ end }}_PASSWORD
              {{- if .Values.mysql.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
                  key: {{ .Values.mysql.secret.passwordKey | quote }}
              {{- else }}
              value: {{ .Values.mysql.options.password | quote }}
              {{- end }}
            - name: {{ if eq .Values.image.mysql.repository "mariadb"}}MARIADB{{ else }}MYSQL{{ end }}_ROOT_PASSWORD
              {{- if .Values.mysql.secret.enabled }}
              valueFrom:
                secretKeyRef:
                  name: {{ if .Values.mysql.secret.name }}{{ .Values.mysql.secret.name }}{{ else }}{{ .Release.Name }}-mysql{{ end }}
                  key: {{ .Values.mysql.secret.rootPasswordKey | quote }}
              {{- else }}
              value: {{ .Values.mysql.options.rootPasswordKey | quote }}
              {{- end }}
          {{- range .Values.mysql.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: "database"
              mountPath: /var/lib/mysql
      volumes:
        - name: "database"
  {{- if .Values.mysql.settings.persistence.claimRetentionPolicy }}
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ .Values.mysql.settings.persistence.claimRetentionPolicy.whenDeleted | default "Retain" | quote }}
    whenScaled: {{ .Values.mysql.settings.persistence.claimRetentionPolicy.whenScaled | default "Retain" | quote }}
  {{- end }}
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "database"
        namespace: "{{ if eq .Release.Namespace "default" }}<<<APPNAME>>>-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
      spec:
        accessModes:
        {{- if .Values.mysql.settings.persistence.accessModes }}
          {{- toYaml .Values.mysql.settings.persistence.accessModes | nindent 8 }} 
        {{- else }}
          - ReadWriteOnce
        {{- end }}
        resources:
          requests:
            storage: "{{ .Values.resources.requests.mysql.storage }}"
{{- end }}

