image:
  web:
    repository: adguard/adguardhome
    pullPolicy: IfNotPresent
    #tag: 0.107.55

global:
  web:
    ports:
      #########################
      ###     Plain DNS     ###
      #########################
      - containerPort: 53
        protocol: UDP
        hostPort: 53
      - containerPort: 53
        protocol: TCP
        hostPort: 53
      #########################
      ###   DNS over QUIC   ###
      #########################
      - containerPort: 784
        protocol: UDP
      - containerPort: 853
        protocol: UDP
      - containerPort: 853
        protocol: TCP
      - containerPort: 8853
        protocol: UDP
      #########################
      ###   Initial setup   ###
      #########################
      - containerPort: 3000
        protocol: TCP
      #########################
      ###     Web server    ###
      #########################
      - containerPort: 80
        protocol: TCP
      - containerPort: 443
        protocol: TCP
      #########################
      ###  DNSCrypt Server  ###
      #########################
      - containerPort: 5443
        protocol: TCP
      - containerPort: 5443
        protocol: UDP
    environments: {}
      # - name: key
      #  value: value


service:
  type: ClusterIP
  ports:
    - name: dns-tcp
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: 53
      protocol: UDP
    - name: dns-over-quic-udp-784
      port: 784
      targetPort: 784
      protocol: UDP
    - name: dns-over-quic-udp-853
      port: 853
      targetPort: 853
      protocol: UDP
    - name: dns-over-quic-tcp-853
      port: 853
      targetPort: 853
      protocol: TCP
    - name: dns-over-quic-udp-8853
      port: 8853
      targetPort: 8853
      protocol: UDP
    - name: initial-setup
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: web
      port: 80
      targetPort: 80
      protocol: TCP
    - name: web-ssl
      port: 443
      targetPort: 443
      protocol: TCP
    - name: dnscrypt-server-tcp
      port: 5443
      targetPort: 5443
      protocol: TCP
    - name: dnscrypt-server-udp
      port: 5443
      targetPort: 5443
      protocol: UDP


resources:
  limits:
    web:
      memory: 512Mi
  requests:
    web:
      storage: 2Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
