image:
  web:
    repository: redmine
    pullPolicy: IfNotPresent
    #tag: 6.0.4
  postgres:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: 17
  mysql:
    repository: mariadb
    pullPolicy: IfNotPresent
    tag: 11.6

global:
  web:
    ports:
      - containerPort: 3000
    environments: {}
      # - name: key
      #  value: value

  postgres:
    selected: true
    external:
      enabled: false
      host: 127.0.0.1
      port: 5432
    internal:
      enabled: true
    cnpg:
      enabled: false
      replicas: 3
      primaryUpdateStrategy: unsupervised
    secret:
      enabled: true
      autoCreate: true
      name: redmine-postgres
      usernameKey: username
      passwordKey: password
      databaseKey: database
    options:
      database: redmine
      username: redmine
      password: redmine
    settings: #~ ignored if cnpg.enabled
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments:
      {}
      # - name: key
      #   value: value

  mysql:
    selected: false
    external:
      enabled: false
      host: 127.0.0.1
      port: 3306
    internal:
      enabled: true
    secret:
      enabled: true
      autoCreate: true
      name: redmine-mysql
      usernameKey: mysql_username
      passwordKey: mysql_password
      rootPasswordKey: mysql_root_password
      databaseKey: mysql_database
    options:
      database: redmine
      username: redmine
      password: redmine
      rootPassword: my_secret_root_password
    settings:
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}
      # - name: key
      #   value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

resources:
  limits:
    web:
      memory: 512Mi
    postgres:
      memory: 512Mi
    mysql:
      memory: 512Mi
  requests:
    web:
      storage: 1Gi
    postgres:
      storage: 1Gi
    mysql:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
