---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-main"
  namespace: "{{ if eq .Release.Namespace "default" }}maddy-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  replicas: {{ .Values.replicaCount | default (printf "%d" 1) }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}-main"
  template:
    metadata:
      labels:
        app: "{{ .Release.Name }}-main"
    spec:
    {{- with .Values.nodeSelector }}
      nodeSelector:
      kubernetes.io/arch: amd64
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: "{{ .Release.Name }}-main"
          image: {{ template "maddy.main.image" . }}
          command:
            - sh
            - -c
            - |
              maddy --config $MADDY_CONFIG
          env:
            - name: MADDY_CONFIG
              value: /app/config/maddy.conf
            - name: MADDY_HOSTNAME
              value: {{ .Values.main.options.hostname | quote }}
            - name: MADDY_DOMAIN
              value: {{ .Values.main.options.domain | quote }}
          {{- range .Values.main.environments }}
            - name: {{ .name }}
              value: {{ .value | quote }}
          {{- end }}
          {{- with .Values.main.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources.limits.main }}
          resources:
            limits:
              {{- toYaml . | nindent 14 }}
          {{- end }}
          volumeMounts:
            - name: "{{ .Release.Name }}-data"
              mountPath: /data
            - name: "{{ .Release.Name }}-config"
              mountPath: /app/config
              {{- if .Values.main.tls.enabled }}
            - name: "{{ .Release.Name }}-ssl"
              mountPath: /app/tls
              {{- end }}
      volumes:
        - name: "{{ .Release.Name }}-data"
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data-pvc"
        - name: "{{ .Release.Name }}-config"
          configMap:
            name: "{{ .Release.Name }}-config"
          {{- if .Values.main.tls.enabled }}
        - name: "{{ .Release.Name }}-ssl"
          secret:
            secretName: "{{ .Values.main.tls.secretName }}"
          {{- end }}