{{ range .Values.global.main.accounts }}
  {{- if and .secret.enabled (eq (.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secret.name }}
  namespace: "{{ if eq $.Release.Namespace "default" }}anki-server-k8s{{ else }}{{ $.Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .secret.key }}: {{ printf "%s:%s" .name .password | b64enc }}
    {{- end }}
{{- end }}