{{- if and .Values.secret.settings.enabled (eq (.Values.secret.settings.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.secret.settings.name }}{{ .Values.secret.settings.name }}{{ else }}{{ .Release.Name }}-main{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}radicale-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.secret.settings.usernameKey }}: "{{ .Values.secret.options.username | b64enc }}"
  {{ .Values.secret.settings.passwordKey }}: "{{ .Values.secret.options.password | b64enc }}"
{{- end }}