image:
  web:
    repository: neosmemo/memos
    pullPolicy: IfNotPresent
    #tag: 1.32.0
  postgres:
    repository: postgres
    pullPolicy: IfNotPresent
    tag: 17

global:
  web:
    ports:
      - containerPort: 5230
    options:
      memos_driver: postgres
    environments: {}
      # - name: key
      #  value: value

  postgres:
    external:
      enabled: false
      host: 127.0.0.1
      port: 5432
    internal:
      enabled: true
    cnpg:
      enabled: false
      replicas: 3
      primaryUpdateStrategy: unsupervised
    secret:
      enabled: true
      autoCreate: true
      name: memos-postgres
      usernameKey: username
      passwordKey: password
      databaseKey: database
    options:
      database: memos
      username: memos
      password: memos
      sslmode: disable
    settings: #~ ignored if cnpg.enabled
      podManagementPolicy: Parallel
      updateStrategy:
        type: RollingUpdate
      persistence:
        accessModes:
          - ReadWriteOnce
        claimRetentionPolicy: 
          whenDeleted: Retain
          whenScaled: Retain
    environments: {}
      # - name: key
      #   value: value

service:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5230
      targetPort: 5230

resources:
  limits:
    web:
      memory: 512Mi
    postgres:
      memory: 512Mi
  requests:
    web:
      storage: 256Mi
    postgres:
      storage: 1Gi

replicaCount: 1

nodeSelector: {}

tolerations: []

affinity: {}
