{{- if and .Values.main.appSecret.enabled (eq (.Values.main.appSecret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.main.appSecret.name }}{{ .Values.main.appSecret.name }}{{ else }}{{ .Release.Name }}-secret{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}nightscout-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.main.appSecret.key }}: "{{ .Values.main.options.app_secret | b64enc }}"
{{- end }}

{{- if and .Values.mongo.secret.enabled (eq (.Values.mongo.secret.autoCreate | toString) "true") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ if .Values.mongo.secret.name }}{{ .Values.mongo.secret.name }}{{ else }}{{ .Release.Name }}-mongo{{ end }}
  namespace: "{{ if eq .Release.Namespace "default" }}nightscout-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
type: Opaque
data:
  {{ .Values.mongo.secret.usernameKey }}: "{{ .Values.mongo.options.username | b64enc }}"
  {{ .Values.mongo.secret.passwordKey }}: "{{ .Values.mongo.options.password | b64enc }}"
  {{ .Values.mongo.secret.databaseKey }}: "{{ .Values.mongo.options.database | b64enc }}"
{{- end }}