---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-main"
  namespace: "{{ if eq .Release.Namespace "default" }}nightscout-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  type: "{{ .Values.service.type }}"
  selector:
    app: "{{ .Release.Name }}-main"
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}

{{ if and .Values.mongo.internal.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-mongo"
  namespace: "{{ if eq .Release.Namespace "default" }}nightscout-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  ports:
    - port: 27017
  selector:
    app: "{{ .Release.Name }}-mongo"
{{- end }}