name: Release Charts

on:
    # push:
    #     branches:
    #         - main
    #     paths:
    #         - 'charts/**'
    workflow_run:
        workflows: ['Update Helm Chart Version']
        types:
            - completed
    workflow_dispatch:

jobs:
    release:
        permissions:
            contents: write
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Check for Changes
              id: check_changes
              run: |
                  if git diff --quiet -- charts/**; then
                    echo "changes=false" >> $GITHUB_ENV
                  else
                    echo "changes=true" >> $GITHUB_ENV
                  fi

            - name: Configure Git
              if: env.changes == 'true'
              run: |
                  git config user.name "$GITHUB_ACTOR"
                  git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

            - name: Install Helm
              if: env.changes == 'true'
              uses: azure/setup-helm@v4
              env:
                  GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

            - name: Run chart-releaser
              if: env.changes == 'true'
              uses: helm/chart-releaser-action@v1.6.0
              with:
                  charts_dir: 'charts'
              env:
                  CR_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
