{{ if and .Values.global.postgres.internal.enabled .Values.global.postgres.selected }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-postgres-pvc"
  namespace: "{{ if eq .Release.Namespace "default" }}umami-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.resources.requests.postgres.storage }}"
{{- end }}

{{ if and .Values.global.mysql.internal.enabled .Values.global.mysql.selected }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-mysql-pvc"
  namespace: "{{ if eq .Release.Namespace "default" }}umami-k8s{{ else }}{{ .Release.Namespace }}{{ end }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.resources.requests.mysql.storage }}"
{{- end }}